// swift-tools-version:5.9
// Generated by scripts/release/swift-dist.mjs from packages/ios at version 0.1.0-beta.5.
// Don't edit here: change the monorepo and release again.
import PackageDescription

let package = Package(
    name: "Sinua",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "CoreEngine", targets: ["CoreEngine"]),
        // Native audio -> the engine's voice opts (docs/audio-pipeline.md, *Native*).
        // Separate product so an app that never touches the mic doesn't link it.
        .library(name: "SinuaVoice", targets: ["SinuaVoice"]),
        // Drop-in SwiftUI renderer: SinuaView(spec:voice:) + the shared paint contract (docs/fx-view.md).
        .library(name: "Sinua", targets: ["Sinua"]),
        // Gemini Live VoiceSource (docs/audio-pipeline.md, *Native Gemini Live*).
        // Foundation-only (URLSessionWebSocketTask); its own product so the
        // socket code isn't linked by apps that don't use it.
        .library(name: "SinuaGeminiLive", targets: ["SinuaGeminiLive"]),
        // ElevenLabs Agents VoiceSource (docs/audio-pipeline.md, *Native ElevenLabs*); Foundation only.
        .library(name: "SinuaElevenLabs", targets: ["SinuaElevenLabs"]),
    ],
    targets: [
        .binaryTarget(
            name: "core_engineFFI",
            url: "https://github.com/sinua-dev/sinua-swift/releases/download/0.1.0-beta.5/core_engineFFI.xcframework.zip",
            checksum: "d8349e8c241ae67a65cbe161774692386174d6274c400f4642e3d14fad73a700"
        ),
        .target(
            name: "CoreEngine",
            dependencies: ["core_engineFFI"],
            path: "Sources/CoreEngine"
        ),
        // The voice *types* only (VoiceSource, VoiceOverrides, AgentState): Foundation, no
        // audio I/O. The views depend on this, not on SinuaVoice, so an app that only draws
        // doesn't link the microphone code (release decision 0.4). Internal:
        // SinuaVoice and Sinua both re-export it, so it's never imported directly.
        .target(
            name: "SinuaVoiceTypes",
            path: "Sources/SinuaVoiceTypes"
        ),
        .target(
            name: "SinuaVoice",
            dependencies: ["SinuaVoiceTypes"],
            path: "Sources/SinuaVoice"
        ),
        .target(
            name: "Sinua",
            dependencies: ["CoreEngine", "SinuaVoiceTypes"],
            path: "Sources/Sinua"
        ),
        .target(
            name: "SinuaGeminiLive",
            dependencies: ["SinuaVoice"],
            path: "Sources/SinuaGeminiLive"
        ),
        .target(
            name: "SinuaElevenLabs",
            dependencies: ["SinuaVoice"],
            path: "Sources/SinuaElevenLabs"
        ),
    ]
)
